import 'server-only'

/**
 * Pairing code issuance.
 *
 * The code is the ONLY credential the extension ever holds before it has
 * tokens, so it is deliberately hostile to reuse:
 *
 *   - 60 second lifetime
 *   - single use, consumed inside a conditional UPDATE in /api/extension/pair
 *   - stored only as a keyed hash
 *   - bound to a `state` value the extension generated and kept locally
 *
 * It is never placed in a URL. The connect page renders it into the DOM and
 * the extension's content script — which has host access to our domain and
 * nothing else — reads it from there. That keeps the code out of browser
 * history, out of referer headers, and out of server logs.
 */
import { PAIRING_CODE_TTL_SECONDS, hashToken, mintPairingCode } from '@/lib/extension/tokens'
import { createAdminClient } from '@/lib/supabase/admin'

export type PairingRequest = {
  userId: string
  /** CSRF value generated by the extension and echoed back at exchange time. */
  state: string
  label: string
  browser: string | null
  platform: string | null
}

/**
 * Issues a code for an already-authenticated user.
 *
 * ⚠️ `userId` must come from a verified session. This function does not
 * authenticate; the caller has already done so.
 */
export async function createPairing(input: PairingRequest): Promise<string> {
  const code = mintPairingCode()
  const codeHash = hashToken(code)

  if (!codeHash) {
    throw new Error('createPairing: no signing secret configured')
  }

  const admin = createAdminClient()
  const expiresAt = new Date(Date.now() + PAIRING_CODE_TTL_SECONDS * 1000)

  // Clear any earlier unconsumed code for this user so a stale one left open
  // in another tab cannot be exchanged later.
  await admin
    .from('extension_pairings')
    .update({ consumed_at: new Date().toISOString() })
    .eq('user_id', input.userId)
    .is('consumed_at', null)

  const { error } = await admin.from('extension_pairings').insert({
    user_id: input.userId,
    code_hash: codeHash,
    state: input.state,
    label: input.label,
    browser: input.browser,
    platform: input.platform,
    expires_at: expiresAt.toISOString(),
  })

  if (error) {
    throw new Error(`createPairing failed: ${error.message}`)
  }

  return code
}
