import { describe, expect, it } from 'vitest'

import { decodeCfEmail, decodeCfEmailHref } from '@/lib/hubble/extract/cfemail'
import { extractReadable } from '@/lib/hubble/extract/readable'

/*
 * Fabricated payloads, generated by XORing a fabricated address against a
 * chosen key — the same scheme Cloudflare uses. No real page, no real person
 * (CLAUDE.md: fixtures are fabricated only).
 */
const HELLO = '7a121f1616153a1b19171f54191517' // hello@acme.com, key 0x7a
const ADA = '1f7e7b7e317370697a737e7c7a5f7e7c727a317c7072' // ada.lovelace@acme.com, key 0x1f
const PRESS = '0070726573734061636d652e636f6d' // press@acme.com, key 0x00

describe('decodeCfEmail', () => {
  it('decodes a payload', () => {
    expect(decodeCfEmail(HELLO)).toBe('hello@acme.com')
    expect(decodeCfEmail(ADA)).toBe('ada.lovelace@acme.com')
  })

  it('handles a zero key, where the payload is plain hex ASCII', () => {
    expect(decodeCfEmail(PRESS)).toBe('press@acme.com')
  })

  it('accepts upper-case hex and surrounding whitespace', () => {
    expect(decodeCfEmail(`  ${HELLO.toUpperCase()}  `)).toBe('hello@acme.com')
  })

  it('normalises to lower case', () => {
    // Cloudflare preserves the author's capitalisation; addresses are stored
    // lower-cased everywhere else in the product.
    const encoded = '7a' + [...'Hello@Acme.com'].map((c) => (c.charCodeAt(0) ^ 0x7a).toString(16).padStart(2, '0')).join('')
    expect(decodeCfEmail(encoded)).toBe('hello@acme.com')
  })
})

describe('decodeCfEmail refuses rather than guesses', () => {
  it.each([
    ['empty', ''],
    ['null', null],
    ['undefined', undefined],
    ['too short to hold a key and a byte', 'a1'],
    ['odd length', '7a121f1616153a1b19171f5419151'],
    ['not hex', 'zzzz1f1616153a1b19171f54191517'],
  ])('returns null for %s', (_label, input) => {
    expect(decodeCfEmail(input)).toBeNull()
  })

  it('returns null when the decoded bytes are not printable', () => {
    // A wrong key yields control characters. Salvaging them would manufacture
    // an address, which is the exact failure rule 4 forbids.
    expect(decodeCfEmail('ff121f1616153a1b19171f54191517')).toBeNull()
  })

  it('returns null when the plaintext decodes cleanly but is not an address', () => {
    const notAnEmail = '7a' + [...'just some words'].map((c) => (c.charCodeAt(0) ^ 0x7a).toString(16).padStart(2, '0')).join('')
    expect(decodeCfEmail(notAnEmail)).toBeNull()
  })

  it('refuses an absurdly long payload instead of decoding it', () => {
    expect(decodeCfEmail('7a' + '12'.repeat(400))).toBeNull()
  })
})

describe('decodeCfEmailHref', () => {
  it('decodes Cloudflare’s rewritten mailto link', () => {
    expect(decodeCfEmailHref(`/cdn-cgi/l/email-protection#${HELLO}`)).toBe('hello@acme.com')
  })

  it('decodes it on an absolute URL too', () => {
    expect(decodeCfEmailHref(`https://acme.com/cdn-cgi/l/email-protection#${HELLO}`)).toBe(
      'hello@acme.com',
    )
  })

  it('ignores an ordinary link', () => {
    expect(decodeCfEmailHref('/contact')).toBeNull()
    expect(decodeCfEmailHref(null)).toBeNull()
  })
})

describe('extractReadable recovers protected addresses', () => {
  it('decodes a span in the page body', () => {
    const page = extractReadable(
      `<html><body><main><p>Reach us at
         <a class="__cf_email__" data-cfemail="${HELLO}">[email&#160;protected]</a>
       </p></main></body></html>`,
      'https://acme.com/contact',
    )

    expect(page.structured.emails).toContain('hello@acme.com')
  })

  it('⚠️ decodes an address in the FOOTER, which the strip pass removes', () => {
    /*
     * The case this whole module exists for. A company contact address most
     * often sits in the footer, and <footer> is stripped as boilerplate — so
     * decoding after the strip would find nothing on exactly the pages worth
     * rescuing. This test fails if the decode is ever reordered after STRIP.
     */
    const page = extractReadable(
      `<html><body><main><p>About us.</p></main>
       <footer><a class="__cf_email__" data-cfemail="${PRESS}">[email&#160;protected]</a></footer>
       </body></html>`,
      'https://acme.com/about',
    )

    expect(page.structured.emails).toContain('press@acme.com')
  })

  it('decodes the rewritten link form', () => {
    const page = extractReadable(
      `<html><body><main>
         <a href="/cdn-cgi/l/email-protection#${ADA}">[email&#160;protected]</a>
       </main></body></html>`,
      'https://acme.com/team',
    )

    expect(page.structured.emails).toContain('ada.lovelace@acme.com')
  })

  it('replaces the placeholder so the model never reads “[email protected]”', () => {
    const page = extractReadable(
      `<html><body><main><p>Contact
         <a class="__cf_email__" data-cfemail="${HELLO}">[email&#160;protected]</a>
       </p></main></body></html>`,
      'https://acme.com/contact',
    )

    expect(page.text).toContain('hello@acme.com')
    expect(page.text).not.toContain('[email')
  })

  it('leaves a page with a bad payload untouched rather than inventing one', () => {
    const page = extractReadable(
      `<html><body><main><a class="__cf_email__" data-cfemail="ffff">[email&#160;protected]</a></main></body></html>`,
      'https://acme.com/contact',
    )

    expect(page.structured.emails).toEqual([])
  })

  it('does not disturb ordinary mailto extraction', () => {
    const page = extractReadable(
      `<html><body><main><a href="mailto:plain@acme.com">mail</a></main></body></html>`,
      'https://acme.com/contact',
    )

    expect(page.structured.emails).toContain('plain@acme.com')
  })
})
