import { createHmac } from 'node:crypto'

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import {
  createSessionGuard,
  readSessionGuard,
  sessionGuardExpired,
  SESSION_ABSOLUTE_SECONDS,
  SESSION_IDLE_SECONDS,
} from '@/lib/auth/session-guard'

describe('session guard', () => {
  beforeEach(() => { process.env.SESSION_GUARD_SECRET = 'test-session-secret-long-enough' })
  afterEach(() => { delete process.env.SESSION_GUARD_SECRET })

  it('signs and verifies issue and activity timestamps', () => {
    const value = createSessionGuard(200, 100)
    expect(readSessionGuard(value)).toMatchObject({ issuedAt: 100, activeAt: 200 })
    expect(readSessionGuard(value)?.sessionId).toMatch(/^[A-Za-z0-9_-]{16,64}$/)
  })

  it('rejects tampering', () => {
    const value = createSessionGuard(200, 100)!
    expect(readSessionGuard(value.replace('100.200', '101.200'))).toBeNull()
  })

  it('enforces idle and absolute timeouts', () => {
    const guard = { sessionId: 'test-session-id-1234', issuedAt: 100, activeAt: 200 }
    expect(sessionGuardExpired(guard, 200 + SESSION_IDLE_SECONDS + 1)).toBe(true)
    expect(sessionGuardExpired(guard, 100 + SESSION_ABSOLUTE_SECONDS + 1)).toBe(true)
    expect(sessionGuardExpired(guard, 300)).toBe(false)
  })

  it('keeps one opaque session id while activity is refreshed', () => {
    const first = readSessionGuard(createSessionGuard(200, 100))!
    const refreshed = readSessionGuard(createSessionGuard(300, first))!

    expect(refreshed.sessionId).toBe(first.sessionId)
    expect(refreshed.issuedAt).toBe(100)
    expect(refreshed.activeAt).toBe(300)
  })

  it('upgrades the former timestamp-only cookie without signing the user out', () => {
    const legacy = createSessionGuard(200, 100)!
    const [, issuedAt, activeAt] = legacy.split('.')
    // Re-sign the legacy payload through a fixture generated by the old shape.
    const payload = `${issuedAt}.${activeAt}`
    const legacySignature = createHmac('sha256', process.env.SESSION_GUARD_SECRET!)
      .update(`outlio-session:${payload}`)
      .digest('base64url')

    expect(readSessionGuard(`${payload}.${legacySignature}`)).toEqual({
      sessionId: null,
      issuedAt: 100,
      activeAt: 200,
    })
  })
})
